// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBwruM6ubNy8dPG3QuLtM1a2ySpBE3bDzY',
    appId: '1:672809166043:web:435f01eaf5eacc4fc518fe',
    messagingSenderId: '672809166043',
    projectId: 'parcial4-24850',
    authDomain: 'parcial4-24850.firebaseapp.com',
    databaseURL: 'https://parcial4-24850-default-rtdb.firebaseio.com',
    storageBucket: 'parcial4-24850.appspot.com',
    measurementId: 'G-GR936QE03W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBttzorjqe05Ag6GaeD0dOAO7cj7n1taZY',
    appId: '1:672809166043:android:92792e1c6f170c5cc518fe',
    messagingSenderId: '672809166043',
    projectId: 'parcial4-24850',
    databaseURL: 'https://parcial4-24850-default-rtdb.firebaseio.com',
    storageBucket: 'parcial4-24850.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCSi-OIaaJtxxvNKmozsnETAE_VkvSUmK4',
    appId: '1:672809166043:ios:021410be23f927b7c518fe',
    messagingSenderId: '672809166043',
    projectId: 'parcial4-24850',
    databaseURL: 'https://parcial4-24850-default-rtdb.firebaseio.com',
    storageBucket: 'parcial4-24850.appspot.com',
    iosClientId: '672809166043-39jskomgtmoobln0p85i8st3abhjev66.apps.googleusercontent.com',
    iosBundleId: 'com.example.parcial4jonathandagoberto',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCSi-OIaaJtxxvNKmozsnETAE_VkvSUmK4',
    appId: '1:672809166043:ios:ff08a8c953a4eafec518fe',
    messagingSenderId: '672809166043',
    projectId: 'parcial4-24850',
    databaseURL: 'https://parcial4-24850-default-rtdb.firebaseio.com',
    storageBucket: 'parcial4-24850.appspot.com',
    iosClientId: '672809166043-g1sqifengrllkdfr9h2c9t750r6boffi.apps.googleusercontent.com',
    iosBundleId: 'com.example.parcial4jonathandagoberto.RunnerTests',
  );
}
